### ISSUE TITLE
Icon keys gets double slashes as the initial characters

### ISSUE THREAD

**Issue by Nerderer** [lazaroofarrill/svg-stringify#1]
So I run:

`svg-stringify src/assets/svg-icons/`

This correctly generates two files, "import-svg-icons.d.ts" and "import-svg-icons.js" in the svg folder.

However, the result looks like this:

`
export const icons = {
  '\\close': 'M0.292512 14.2931C-0.0981549 14.6837 -0.0974882 15.3171 0.292512 15.7077C0.682512 16.0984 1.31651 16.0977 1.70718 15.7077L7.88184 9.53373C7.94718 9.4684 8.05251 9.4684 8.11784 9.53373L14.2925 15.7091C14.6832 16.0997 15.3165 16.0997 15.7072 15.7091C16.0978 15.3184 16.0978 14.6851 15.7072 14.2944L9.53318 8.11773C9.46784 8.0524 9.46784 7.94706 9.53318 7.88173L15.7085 1.70706C16.0992 1.31573 16.0985 0.682396 15.7072 0.291729C15.3158 -0.0989373 14.6825 -0.0982707 14.2925 0.293063L8.11784 6.4664C8.05251 6.53173 7.94718 6.53173 7.88184 6.4664L1.70718 0.293063C1.31651 -0.097604 0.683178 -0.097604 0.292512 0.292396C-0.0981549 0.682396 -0.0981549 1.3164 0.292512 1.70706L6.46651 7.88173C6.53184 7.94706 6.53184 8.0524 6.46651 8.11773L0.292512 14.2931Z@@@@|0 0 16 16',
  '\\delete': 'M11.375 4.375H2.62498C2.46398 4.375 2.33331 4.50567 2.33331 4.66667V12.8333C2.33331 13.4779 2.8554 14 3.49998 14H10.5C11.1446 14 11.6666 13.4779 11.6666 12.8333V4.66667C11.6666 4.50567 11.536 4.375 11.375 4.375ZM5.97915 11.9583C5.97915 12.1998 5.78315 12.3958 5.54165 12.3958C5.30015 12.3958 5.10415 12.1998 5.10415 11.9583V6.70833C5.10415 6.46683 5.30015 6.27083 5.54165 6.27083C5.78315 6.27083 5.97915 6.46683 5.97915 6.70833V11.9583ZM8.89581 11.9583C8.89581 12.1998 8.69981 12.3958 8.45831 12.3958C8.21681 12.3958 8.02081 12.1998 8.02081 11.9583V6.70833C8.02081 6.46683 8.21681 6.27083 8.45831 6.27083C8.69981 6.27083 8.89581 6.46683 8.89581 6.70833V11.9583ZM12.8333 2.33333H10.0625C9.98198 2.33333 9.91665 2.268 9.91665 2.1875V1.45833C9.91665 0.65275 9.2639 0 8.45831 0H5.54165C4.73606 0 4.08331 0.65275 4.08331 1.45833V2.1875C4.08331 2.268 4.01798 2.33333 3.93748 2.33333H1.16665C0.844646 2.33333 0.583313 2.59467 0.583313 2.91667C0.583313 3.23867 0.844646 3.5 1.16665 3.5H12.8333C13.1553 3.5 13.4166 3.23867 13.4166 2.91667C13.4166 2.59467 13.1553 2.33333 12.8333 2.33333ZM5.24998 2.1875V1.45833C5.24998 1.29733 5.38065 1.16667 5.54165 1.16667H8.45831C8.61931 1.16667 8.74998 1.29733 8.74998 1.45833V2.1875C8.74998 2.268 8.68465 2.33333 8.60415 2.33333H5.39581C5.31531 2.33333 5.24998 2.268 5.24998 2.1875Z@@@@|0 0 14 14'
}
`

All the keys have double backslashes at the beginning. If I manually remove these slashes they'll work like intended.

I'm using Windows and Node v14.16.0.

**Comment by lazaroofarrill** [comment]
Yeah, I don't work in Windows very often so I didn't bother in handling windows path styles. Let me know if the update works for you.
